onbloc/gnoscan

.env.main, .gitignore, Dockerfile.main, src/components/view/datatable/account-detail/account-detail.tsx, src/components/view/datatable/block-detail/block-detail.tsx, src/components/view/datatable/item/tx-hash.tsx, src/components/view/datatable/realm-detail/realm-detail.tsx, src/components/view/datatable/token-detail/token-detail.tsx, src/components/view/datatable/transaction/transaction.tsx, src/middleware.ts, src/pages/search/index.tsx, src/pages/transactions/details.tsx, src/repositories/api/fetchers/api-transaction-details.ts, src/repositories/api/selector/select-transaction-details.ts
- Change the transaction details URL
- Fix transaction details
=> Release v0.3.3 to Main

src/components/view/datatable/account-detail/account-detail.tsx, src/components/view/datatable/block-detail/block-detail.tsx, src/components/view/datatable/realm-detail/realm-detail.tsx, src/components/view/datatable/token-detail/token-detail.tsx, src/components/view/datatable/transaction/transaction.tsx
=> Release v0.3.4 to Main

src/repositories/api/selector/select-info-card.ts
- fix: Fix rounding of total transaction fees
=> Hotfix v0.3.3 to Main

src/pages/transactions/details.tsx
- Fix text style on transaction detail page
=> Hotfix v0.3.6 to Main

src/common/hooks/use-network.tsx, src/common/utils/template.utils.ts, src/common/values/url.constant.ts, src/components/ui/badge/badge.tsx, src/components/ui/detail-page-common-styles/index.tsx, src/pages/realms/details.tsx, src/states/index.ts, src/states/network.ts, src/styles/theme.ts
Based on issue #94 ,
Link to an interactive page in Gnostudio.
- Define a URL template for GnoStudio
- Add a link button to the Realm detail page
=> feat: Add GnoStudio connect link

src/common/hooks/tokens/use-token.ts, src/pages/tokens/[...path].tsx
Apply the token's decimals to the total supply value on the token details page.
=> feat: apply decimals to grc20 tokens

src/components/ui/text/amount-text.tsx
- Fixes an issue that prevented showing the number of formatted strings.
- Improve the structure of the component.
=> fix: resolve numbers that non-display

src/common/hooks/main/use-total-gas-info.ts, src/components/ui/text/amount-text.tsx, src/components/view/main-realm/total-gas-share/total-gas-share.tsx
When calculating gas fees, the gas fee value is calculated instead of the gas used value.
=> fix: change gas used to fee

src/common/clients/indexer-client/indexer-client.ts, src/common/hooks/main/use-transaction-summary-info.ts, src/common/react-query/transaction/queries.ts, src/repositories/account-repository/account-repository.ts, src/repositories/account-repository/query.ts, src/repositories/transaction-repository/query.ts, src/repositories/transaction-repository/transaction-repository.ts
Maximum element processed per indexer query throws an error and throws an exception.
=> fix: max elements processed per indexer query

src/common/clients/node-client/node-rpc-client.ts, src/common/hooks/blocks/use-block.ts, src/common/hooks/tokens/use-token-transactions-onbloc.ts, src/common/hooks/tokens/use-token-transactions.ts, src/common/hooks/tokens/use-token.ts, src/common/react-query/realm/queries.ts, src/common/react-query/realm/types.ts, src/components/view/datatable/token-detail/token-detail-page.tsx, src/pages/tokens/[...path].tsx, src/repositories/account-repository/account-repository.ts, src/repositories/account-repository/onbloc-account-repository.ts, src/repositories/realm-repository.ts/mapper.ts, src/repositories/realm-repository.ts/onbloc-query.ts, src/repositories/realm-repository.ts/onbloc-realm-repository.ts, src/repositories/realm-repository.ts/query.ts, src/repositories/realm-repository.ts/realm-repository.ts, src/repositories/realm-repository.ts/types.ts, src/repositories/response/transaction.mapper.ts, src/repositories/transaction-repository/onbloc-transaction-repository.ts, src/repositories/transaction-repository/transaction-repository.ts, src/repositories/utility.ts
The token's transaction list shows the transactions that contain the token event.
=> feat: support token transactions and events

src/styles/global-style.ts
Remove the white area from the main screen.
=> fix: remove white space

src/common/react-query/account/queries.ts, src/repositories/account-repository/account-repository.ts, src/repositories/account-repository/onbloc-account-repository.ts, src/repositories/account-repository/onbloc-query.ts, src/repositories/account-repository/query.ts, src/repositories/account-repository/types.ts, src/types/data-type.ts
Get a GRC20 list of accounts based on events.
=> feat: display account tokens by events

src/common/hooks/realms/use-realm.ts, src/components/view/datatable/item/lazy-fee-amount.tsx, src/components/view/datatable/item/lazy-total-calls.tsx, src/components/view/datatable/realm-detail/realm-detail.tsx, src/pages/realms/details.tsx, src/repositories/realm-repository.ts/onbloc-realm-repository.ts, src/repositories/realm-repository.ts/realm-repository.ts
Change the logic for checking transaction fees and number of calls on the Realm list and detail page.
=> fix: adjust realms calls and fees

src/common/hooks/account/use-account.ts, src/components/ui/datatable/datatable.tsx, src/pages/accounts/[address].tsx
Add a loading icon when loading assets in account.
=> feat: add asset loading in account detail

src/common/hooks/realms/use-realms.ts, src/common/react-query/realm/queries.ts, src/common/react-query/realm/types.ts, src/components/view/datatable/item/lazy-fee-amount.tsx, src/components/view/datatable/item/lazy-total-calls.tsx, src/components/view/datatable/realm/realm.tsx, src/repositories/realm-repository.ts/onbloc-query.ts, src/repositories/realm-repository.ts/onbloc-realm-repository.ts, src/repositories/realm-repository.ts/query.ts, src/repositories/realm-repository.ts/realm-repository.ts, src/repositories/realm-repository.ts/types.ts
=> feat: fetch initialize realms data

public/resource/chains.json
=> chore: update chain metadata

src/pages/transactions/details.tsx
Modify the transaction details page to correctly show the Creator item when the message is of type Add Package.
=> fix: displays the creator entry in the add package type transaction

src/components/view/main-card/main-card.tsx, src/repositories/chain-repository/chain-repository.ts
Modify the airdrop supply quantity.
=> chore: change airdrop supply

package.json, yarn.lock
Descriptions
Bumps axios from 1.2.0 to 1.7.3.
=> chore(deps): bump axios from 1.2.0 to 1.7.3

src/common/hooks/common/use-get-simple-transactions.ts, src/common/hooks/main/use-transaction-summary-info.ts, src/repositories/transaction-repository/onbloc-transaction-repository.ts, src/repositories/transaction-repository/transaction-repository.ts
Normalize exposure of the average daily gas fee area on the transaction card on the main screen.
=> fix: average gas fee in total transactions card

src/common/hooks/account/use-account.ts, src/repositories/account-repository/onbloc-account-repository.ts
- Fix message types in the account transaction table.
- Fixes the transaction table showing a blank area when loading transactions after loading is complete.
=> fix: fix the account transaction table

src/assets/meta/test5/validators.json
1. updates test5 validators info
=> feat: update test5 validators info

src/repositories/account-repository/onbloc-query.ts, src/repositories/realm-repository.ts/onbloc-query.ts
Changed the syntax of transaction filters in the indexer.
- Changed to messages -> message.
=> fix: fix tx-indexer query syntax

src/common/clients/indexer-client/types.ts, src/common/react-query/realm/queries.ts, src/repositories/account-repository/onbloc-account-repository.ts, src/repositories/account-repository/onbloc-query.ts, src/repositories/account-repository/query.ts, src/repositories/realm-repository.ts/mapper.ts, src/repositories/realm-repository.ts/onbloc-query.ts, src/repositories/realm-repository.ts/query.ts, src/repositories/realm-repository.ts/realm-repository.ts, src/repositories/realm-repository.ts/types.ts, src/repositories/response/transaction.mapper.ts, src/repositories/response/transaction.types.ts, src/repositories/transaction-repository/onbloc-query.ts, src/repositories/transaction-repository/onbloc-transaction-repository.ts, src/repositories/transaction-repository/query.ts, src/repositories/transaction-repository/transaction-repository.ts
Remove `__typename` so that it is not affected by the indexer's introspection option.
=> feat: remove an indexer's introspection type

src/common/hooks/use-window-size.ts, src/common/values/ui.constant.ts, src/components/view/main-active-list/main-active-list.tsx, src/components/view/main-card/main-card.tsx, src/components/view/main-realm/main-realm.tsx, src/components/view/main-transaction-news/main-transaction-news.tsx, src/containers/home/main-active-list-container/MainActiveListContainer.tsx, src/containers/home/main-card-container/MainCardContainer.tsx, src/containers/home/main-realm-container/MainRealmContainer.tsx, src/containers/home/main-transaction-news-container/MainTransactionNewsContainer.tsx, src/layouts/home/HomeLayout.styles.ts, src/layouts/home/HomeLayout.tsx, src/layouts/home/components/indexer-client-connection-failure-notice/IndexerClientConnectionFailureNotice.styles.ts, src/layouts/home/components/indexer-client-connection-failure-notice/IndexerClientConnectionFailureNotice.tsx, src/pages/index.tsx, src/styles/css/inner-layout.ts
This PR introduces UI layer separation for the Main(Home) page as the first step in our application architecture restructuring. This is part of a larger initiative to establish clear boundaries between different UI concerns across all pages.
- **Pages**: Simplified Main page to serve primarily as a routing entry point
- **Containers**: Added to handle data fetching and business logic
- **Layouts**: Created dedicated layout components for structural organization
- **Components**: Refactored to focus on presentation and reusability
- **Atomic**: Extracted and organized consistently across components
The new architecture creates a clear, predictable data flow:
- Data is fetched and processed in container components
- Processed data flows down to layout and presentation components via props
- …
=> [GNS-255] Implement UI layer separation for main page

src/common/hooks/tokens/use-tokens.ts, src/components/view/datatable/token/index.ts, src/components/view/tokens/token-list-table/TokenListTable.styles.ts, src/components/view/tokens/token-list-table/TokenListTable.tsx, src/containers/tokens/token-list-container/TokenListContainer.tsx, src/layouts/tokens/TokensLayout.styles.ts, src/layouts/tokens/TokensLayout.tsx, src/pages/tokens/index.tsx
This PR introduces UI layer separation for the Tokens page as the first step in our application architecture restructuring. This is part of a larger initiative to establish clear boundaries between different UI concerns across all pages.
- **Pages**: Simplified Tokens page to serve primarily as a routing entry point
- **Containers**: Added to handle data fetching and business logic
- **Layouts**: Created dedicated layout components for structural organization
- **Components**: Refactored to focus on presentation and reusability
- **Atomic**: Extracted and organized consistently across components
The new architecture creates a clear, predictable data flow:
- Data is fetched and processed in container components
- Processed data flows down to layout and presentation components via props
- …
=> [GNS-255] Implement UI layer seperation for tokens page

src/components/view/transaction/transaction-contract-details/StandardNetworkTransactionContractsDetails.tsx, src/components/view/transactions/transaction-list-table/standard-network/StandardNetworkTransactionListTable.tsx
This PR has been modified to match the API response data.
- Modify to match contract list data on the transaction details page
=> hotfix: [GNS-258] MultiMessage Error

src/common/mapper/block/block-mapper.ts, src/models/api/block/block-model.ts
This PR is in response to the changed interface of Block data.
- Update Column
- totalTransactionCount -> transactionCount
=> [GNS-258] BlockList data

src/common/mapper/realm/realm-mapper.ts, src/components/view/main-active-list/active-newest/StandardNetworkActiveNewest.tsx, src/components/view/realm/realm-summary/StandardNetworkRealmSummary.tsx, src/models/api/realm/realm-model.ts
This PR is a mapping of the summary data from the Realm Detail page to the interface.
- Realm Summary
- balance
- totalContractCalls
- totalUsedFees
- Newest Realm
- functionCount 
- totalCalls
=> [GNS-258] Realm Detail Summary DataMapping

src/common/clients/rpc-client/http-rpc-client.ts, src/common/hooks/blocks/use-block.ts, src/common/hooks/blocks/use-blocks.ts, src/common/hooks/use-network.tsx, src/common/react-query/account/queries.ts, src/common/react-query/block/queries.ts, src/common/react-query/chain/queries.ts, src/common/react-query/realm/queries.ts, src/common/react-query/transaction/queries.ts, src/common/utils/common.utility.ts, src/components/ui/loading-spinner/LoadingSpinner.tsx, src/components/ui/network/network.tsx, src/layouts/block/BlockLayout.tsx, src/layouts/home/HomeLayout.tsx, src/layouts/transaction/TransactionLayout.tsx
Added visual feedback and improved data handling during network switches to enhance user experience, particularly for custom network changes.
- Added network switching state tracking
- Implemented loading indicators during network transitions
- Added error handling for failed network switches
=> [GNS-287] Enhance network switching UX with loading states and data refetching

src/components/ui/animation/Animation.tsx, src/components/view/header/btm-nav.tsx, src/pages/_document.tsx
- Layout flickering due to delayed image loading on first service access
- Poor first impression caused by empty image spaces during loading
- Hero section lacks visual impact
- Static design fails to capture user attention effectively
- Implemented image preloading to eliminate layout flickering
- Enhanced initial loading experience for smoother page transitions
- Added dynamic animations to hero section
- Introduced interactive elements responding to user interactions
- Improved visual hierarchy for better information delivery
=> [GNS-288] 🎨 Enhance Hero Section: Add Preloading & Interactive Animations

src/common/react-query/statistics/use-get-total-gas-share.ts, src/components/view/main-realm/total-gas-share/total-gas-share-api.tsx, src/repositories/api/statistics/api-statistics-repository-impl.ts, src/repositories/api/statistics/api-statistics-repository.ts, src/repositories/api/statistics/request/get-total-fee-share-request.ts, src/repositories/api/statistics/request/index.ts, src/repositories/api/statistics/response/get-total-gas-share-response.ts
This PR is an integration with TotalFeeShare data.
=> Total-Fee-Share Data

src/common/utils/token.utility.test.ts, src/common/utils/token.utility.ts, src/components/view/token/token-summary/StandardNetworkTokenSummary.tsx, src/components/view/tokens/token-list-table/standard-network-token-list-table/StandardNetworkTokenListTable.tsx
This PR is an action with token decimalisation applied.
- Added decimal place correction for token's totalSupply display
- Integrated formatTokenDecimal utility function from token.utility
- Now properly formats totalSupply based on token's decimal places
=> [GNS-286]  apply token-decimal digit correction

src/common/clients/indexer-client/indexer-client.ts, src/components/ui/network/network.tsx
Network connectivity improvements: Enhanced RPC and indexer URL validation logic
- Improved validation logic for RPC and indexer URLs when connecting to custom networks.
- Fixed indexer URLs to be handled optionally: if no indexer URL is provided, validation is skipped.
- Clearly handles errors that occur during the connection process and provides feedback to the user.
=> [GNS-287] Enhance network switching UX with error states

src/components/view/token/token-summary/TokenSummary.styles.ts, src/layouts/token/TokenLayout.styles.ts
Data fetching was not working properly when moving links between pages
- Fixed an issue where data fetching failed when clicking the Move Realm button on the Token Details page
- TokenPath copy button
=> fix: Data fetching issue on route change (TokenDetails)

src/common/mapper/realm/realm-mapper.ts, src/common/react-query/block/api/use-get-block-events-by-height.ts, src/common/react-query/block/api/use-get-block-transactions-by-height.ts, src/common/services/block/use-mapped-api-block-events.ts, src/common/services/block/use-mapped-api-block-transactions.ts, src/common/utils/block.utility.test.ts, src/common/utils/block.utility.ts, src/common/values/gno.constant.ts, src/components/view/account/account-transactions/StandardNetworkAccountTransactions.tsx, src/components/view/block/block-info/CustomNetworkBlockInfo.tsx, src/components/view/block/block-info/StandardNetworkBlockInfo.tsx, src/components/view/block/block-summary/StandardNetworkBlockSummary.tsx, src/components/view/datatable/block-detail/block-detail.tsx, src/components/view/datatable/event/StandardNetworkEventDatatable.tsx, src/components/view/datatable/item/block.tsx, src/components/view/datatable/item/publisher.tsx, src/components/view/main-active-list/active-latest-blogs/active-latest-blogs.tsx, src/components/view/realm/realm-summary/StandardNetworkRealmSummary.tsx, src/components/view/transaction/transaction-summary/standard-network-transaction-summary/StandardNetworkTransactionSummary.tsx, src/layouts/transaction/TransactionLayout.tsx, src/repositories/api/block/api-block-repository-impl.ts, src/repositories/api/block/api-block-repository.ts, src/repositories/api/block/request/get-block-events-request.ts, src/repositories/api/block/request/get-block-transactions-request.ts, src/repositories/api/block/request/index.ts, src/repositories/api/block/response/get-block-events-response.ts, src/repositories/api/block/response/get-block-transactions-response.ts
Integration tasks for working with Genesis block data
- Working with Genesis Block (Height: 0) Data
- Processing realm: funcs data
- Handling ‘Genesis’ display when block height is 0
=> [GNS-296] genesis block data

src/common/react-query/statistics/use-get-total-gas-share.ts, src/components/view/main-realm/total-gas-share/total-gas-share-api.tsx, src/repositories/api/statistics/response/get-total-gas-share-response.ts
This PR is an integration with TotalFeeShare data.
=> [GNS-289] TotalFeeShare

src/common/react-query/search/api/use-get-search.ts, src/common/values/search.constant.ts, src/components/ui/search-result/StandardNetworkSearchResult.tsx, src/components/ui/search-result/search-result-item/SearchResultItem.styles.ts, src/components/ui/search-result/search-result-item/SearchResultItem.tsx, src/repositories/api/block/api-block-repository-impl.ts, src/repositories/api/search/api-search-repository-impl.ts, src/repositories/api/search/response/get-search-response.ts
This PR is for Search feature integration development.
- Search result type
- ACCOUNT: Account search
- BLOCK: Search for blocks
- TOKEN: Search for GRC20 tokens
- PROPOSAL: Search for proposals
- REALM: Search for Realm
- TRANSACTION: Search for transactions
=> [GNS-295] Search

src/common/mapper/transaction/transaction-mapper.ts, src/common/utils/message.utility.test.ts, src/common/utils/message.utility.ts, src/common/values/message-types.constant.ts, src/common/values/tooltip-content.constant.tsx, src/components/ui/badge/badge.tsx, src/components/view/datatable/item/type.tsx, src/components/view/transaction/common/TransactionMessageFields.styles.ts, src/components/view/transaction/common/TransactionMessageFields.tsx, src/components/view/transaction/common/index.ts, src/components/view/transaction/transaction-contract-details/StandardNetworkTransactionContractsDetails.tsx, src/components/view/transaction/transaction-contract-details/TransactionContractDetails.styles.ts, src/components/view/transaction/transaction-info/standard-network-transaction-info/StandardNetworkTransactionInfo.tsx, src/components/view/transaction/transaction-message-card/TransactionMessageCard.styles.ts, src/components/view/transaction/transaction-message-card/index.ts, src/components/view/transaction/transaction-message-card/transaction-add-package-message/StandardNetworkAddPackageMessage.tsx, src/components/view/transaction/transaction-message-card/transaction-bank-msg-send-message/StandardNetworkBankMsgSendMessage.tsx, src/components/view/transaction/transaction-message-card/transaction-msg-call-message/StandardNetworkMsgCallMessage.tsx, src/components/view/transaction/transaction-message-card/transaction-msg-run-message/StandardMsgRunMessage.tsx, src/layouts/transaction/TransactionLayout.styles.ts, src/repositories/api/transaction/response/get-transaction-contracts-response.ts
This PR is an informational operation based on the transaction message type.
- Message types
- /vm.m_call
- /vm.m_addpkg
- /vm.m_run
- /bank.MsgSend
- Adding specific conditions
- /vm.m.call > Function type(Transfer)
=> [GNS-279] Transaction message data

src/common/react-query/realm/api/use-get-realm-events-by-path.ts, src/common/react-query/realm/api/use-get-realm-transactions-by-path.ts, src/common/react-query/token/api/use-get-token-transactions-by-id.ts, src/common/react-query/transaction/api/use-get-transaction-contracts-by-hash.ts, src/common/react-query/transaction/api/use-get-transaction-events-by-hash.ts, src/components/view/account/account-transactions/StandardNetworkAccountTransactions.tsx, src/components/view/datatable/token-detail/token-detail-page.tsx, src/components/view/realm/realm-info/StandardNetworkRealmInfo.tsx, src/components/view/transaction/transaction-info/standard-network-transaction-info/StandardNetworkTransactionInfo.tsx, src/repositories/api/realm/api-realm-repository-impl.ts, src/repositories/api/realm/api-realm-repository.ts, src/repositories/api/realm/request/get-realm-events-request.ts, src/repositories/api/realm/request/get-realm-transactions-request.ts, src/repositories/api/realm/request/index.ts, src/repositories/api/realm/response/get-realm-events-response.ts, src/repositories/api/token/api-token-repository-impl.ts, src/repositories/api/token/api-token-repository.ts, src/repositories/api/token/request/get-token-transactions-request.ts, src/repositories/api/token/request/index.ts, src/repositories/api/transaction/api-transaction-repository-impl.ts, src/repositories/api/transaction/api-transaction-repository.ts, src/repositories/api/transaction/request/get-transaction-contracts-request.ts, src/repositories/api/transaction/request/get-transaction-events-request.ts, src/repositories/api/transaction/request/index.ts, src/repositories/api/transaction/response/get-transaction-contracts-response.ts, src/repositories/api/transaction/response/get-transaction-events-response.ts
This PR is an Apply Infinite Query operation.
- Realm
- Transactions
- Events
- Token
- Transactions
- Transaction
- Messages
- Events
=> [GNS-300] ViewMore data

src/components/view/transaction/transaction-summary/custom-network-transaction-summary/CustomNetworkTransactionSummary.tsx, src/components/view/transaction/transaction-summary/standard-network-transaction-summary/StandardNetworkTransactionSummary.tsx, src/containers/transaction/transaction-summary-container/TransactionSummaryContainer.tsx, src/repositories/api/transaction/response/get-transaction-response.ts
This PR is an action that shows more detailed error data on the transaction details page.
- RPC data fetching
- ErrorType
- ErrorLog
- BlockResultLog
=> [GNS-301] Transaction Error info

src/common/mapper/realm/realm-mapper.ts, src/common/utils/format/format-utils.ts, src/components/view/datatable/realm-detail/realm-detail.tsx, src/components/view/datatable/token-detail/token-detail.tsx, src/components/view/realm/realm-info/StandardNetworkRealmInfo.tsx, src/components/view/transactions/transaction-list-table/standard-network/StandardNetworkTransactionListTable.tsx
Improve the UI of the content displayed when hovering over a Function within the Details page.
- Ensure uniformity of content for Function badges in transaction lists
- Coverage:
- Account
- Block
- Realm
- Token
=> [GNS-310] Modify transaction list function hover content

src/components/ui/badge/badge.tsx, src/components/view/datatable/item/event-name.tsx, src/components/view/transaction/common/TransactionMessageFields.styles.ts, src/components/view/transaction/common/TransactionMessageFields.tsx, src/components/view/transaction/transaction-message-card/transaction-add-package-message/StandardNetworkAddPackageMessage.tsx, src/components/view/transaction/transaction-message-card/transaction-msg-call-message/StandardNetworkMsgCallMessage.tsx, src/components/view/transaction/transaction-message-card/transaction-msg-run-message/StandardMsgRunMessage.tsx
This PR is a UI fix for the argument badge list UI
=> [GNS-312] BadgeList UI

src/common/mapper/block/block-mapper.ts, src/common/mapper/transaction/transaction-mapper.ts, src/components/view/transaction/common/TransactionMessageFields.tsx
This PR fixes an issue with timestamp data refinement
=> [GNS-315] Event timestamp

src/components/view/account/account-transactions/StandardNetworkAccountTransactions.tsx, src/components/view/datatable/account-detail/StandardNetworkAccountTxsDatatable.tsx, src/components/view/datatable/item/StandardNetworkAmount.tsx, src/components/view/datatable/item/index.ts
This PR is to map the GRC20 data correctly in the transaction list on the Account detail page
=> [GNS-311] GRC20 Data for AccountDetails

src/components/ui/active-list/active-list.tsx, src/layouts/realm/Realmlayout.styles.ts, src/layouts/token/TokenLayout.styles.ts
- Fixed tooltip positions in Detail pages
- RealmDetail page > Balance column
- TokenDetail page > Path column
- Fixed scroll issue for individual cards in Main page (mobile)
=> [GNS-317] minor UI issue

src/common/mapper/token/token-mapper.ts, src/components/view/account/account-assets/CustomNetworkAccountAssets.tsx, src/components/view/account/account-assets/StandardNetworkAccountAssets.tsx, src/components/view/datatable/item/StandardNetworkTokenTitle.tsx, src/components/view/datatable/item/index.ts, src/components/view/tokens/token-list-table/standard-network-token-list-table/StandardNetworkTokenListTable.tsx, src/layouts/account/components/account-asset-item/AccountAssetItem.tsx, src/models/api/token/token-model.ts, src/repositories/api/account/response/get-account-response.ts, src/repositories/api/token/response/get-tokens-response.ts, src/types/account/asset/index.ts, src/types/account/index.ts, src/types/index.ts
This PR is an action that shows an image of the token logo.
- Update TokenModel Interface
- Create a TokenTitle component for Standard networks
=> [GNS-309] TokenImage for Account, Token pages

src/components/ui/loading/skeleton-bar.tsx, src/components/view/account/account-address/StandardNetweorkAccountAddress.tsx, src/components/view/account/account-assets/StandardNetworkAccountAssets.tsx, src/layouts/account/AccountLayout.tsx, src/layouts/account/components/account-asset-item/AccountAssetItem.tsx
This PR improved the overall UX of the account-detail page.
- Loading TokenLogo
- Account Info handling
=> [GNS-309] Improve AccountDetail page, TokenLogo Skeleton

src/common/react-query/statistics/use-get-summary-accounts.ts, src/common/react-query/statistics/use-get-summary-blocks.ts, src/common/react-query/statistics/use-get-summary-transactions.ts, src/common/values/query.constant.ts
This PR is an action that changed the refetching cycle for dashboard data
- Refetching Interval: 5000ms
=> Update Dashboard summary data refetching interval

src/common/values/number.constant.ts, src/components/view/datatable/event/StandardNetworkEventDatatable.tsx, src/components/view/datatable/item/tx-hash-copy.tsx
This PR is a modification to the TxHash minification policy
- Reduces TxHash display length from 8 to 6 characters to match Caller column format
=> [GNS-329] TxHash ellipsis

src/components/view/main-active-list/main-active-list.tsx, src/components/view/main-realm/main-realm.tsx, src/components/view/main-transaction-news/main-transaction-news.tsx, src/components/view/realms/realm-list-table/standard-network-realm-list-table/StandardNetworkRealmListTable.tsx
This PR is a StorageDeposit integration
- Remove dummy data(storage deposit)
=> [GNS-354] StorageDeposit

src/components/view/transactions/transaction-list-table/standard-network/StandardNetworkTransactionListTable.tsx
Description
This PR is an action in response to a runtime error on the transaction list page.
Details
Improved datatable header generation functions to apply defensive coding for missing data
=> [GNS-356] TransactionList runtime error

src/components/view/transaction/transaction-message-card/transaction-add-package-message/StandardNetworkAddPackageMessage.tsx, src/components/view/transaction/transaction-message-card/transaction-msg-call-message/StandardNetworkMsgCallMessage.tsx, src/components/view/transaction/transaction-message-card/transaction-msg-run-message/StandardNetworkMsgRunMessage.tsx, src/repositories/api/transaction/response/get-transaction-contracts-response.ts
This PR merges the latest version of develop into the main branch.
Changing and responding to MaxDeposit data interface on the transaction details page
=> Merge develop into main (hotfix-max_deposit)

src/components/ui/chart/stacked-bar-chart/stacked-bar-chart2.tsx
This PR is a UI fix for the StorageDeposit graph.
=> [GNS-360 TotalStorageDeposit Graph

src/common/clients/node-client/node-rpc-client.ts, src/common/clients/node-client/types.ts, src/common/hooks/blocks/use-block.ts, src/common/hooks/transactions/use-transaction.ts, src/common/react-query/block/queries.ts, src/common/react-query/transaction/queries.ts, src/common/utils/transaction.utility.ts, src/components/ui/chart/stacked-bar-chart/stacked-bar-chart2.tsx, src/components/view/datatable/block/StandardNetworkBlockDatatable.tsx, src/components/view/datatable/block/block.tsx, src/repositories/block-repository/block-repository.ts, src/repositories/block-repository/onbloc-block-repository.ts, src/repositories/block-repository/types.ts, src/types/data-type.ts, src/types/transaction-messages.types.ts
This PR merges the latest version of develop into the main branch.
- #208
- #209
=> Merge develop into main (#208, #209)
